name: Deploy to Lambda

on:
  push:
    branches:
      - main  # Or your target branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Zip Lambda Function
        run: |
          zip -r function.zip . -x '*.git*' -x '*.github*'

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          function_name: YOUR_LAMBDA_FUNCTION_NAME
          zip_file: function.zip
