name: Deploy to Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Zip Lambda Function
        run: |
          zip -r function.zip . -x '*.git*' -x '*.github*'

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code \
            --function-name amplify-slack-notification \
            --zip-file fileb://function.zip
